apiVersion: apps/v1
kind: Deployment
metadata:
  name: commands-mssql-depl
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: commands-mssql
  template:
    metadata:
      labels:
        app: commands-mssql
    spec:
      containers:
        - name: commands-mssql
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 1433
          env:
            - name: MSSQL_PID
              value: "Express"
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: commands-mssql
                  key: SA_PASSWORD
          volumeMounts:
            - mountPath: /var/opt/mssql/data
              name: commands-mssql
      volumes:
        - name: commands-mssql
          persistentVolumeClaim:
            claimName: commands-mssql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: commands-mssql-clusterip-srv
spec: 
  type: ClusterIP
  selector:
    app: commands-mssql
  ports:
    - name: commands-mssql
      protocol: TCP
      port: 1433
      targetPort: 1433
---
apiVersion: v1
kind: Service
metadata: 
  name: commands-mssql-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: commands-mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433